version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: won_games
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: won_games
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data:/var/lib/postgresql/data